name: build-server
on:
  workflow_call:
    outputs:
      image:
        value: ${{ jobs.docker.outputs.image }}

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/eukarya-inc/plateau-view/plateauview-api:latest
      EXTENSION_IMAGE: ghcr.io/eukarya-inc/plateau-view/plateauview-extension:latest
    outputs:
      image: ${{ env.IMAGE_NAME }}@sha256:${{ steps.docker.outputs.digest }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download extension artifact
        continue-on-error: true
        run: |
          docker pull "$EXTENSION_IMAGE"
          CID=$(docker create "$EXTENSION_IMAGE" /)
          docker cp "$CID":/dist .
          docker rm "$CID"
          shopt -s dotglob
          mv dist/* .
          rmdir dist
      - name: Build docker image
        uses: docker/build-push-action@v3
        id: docker
        with:
          context: ./server
          platforms: linux/amd64
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
