name: Pack
on:
  workflow_dispatch:
    inputs:
      update:
        description: 'Update which products?'
        type: choice
        options:
          - no-update
          - visualizer
          - cms
          - flow
          - all

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: plateau
          path: plateau
      - name: Clean
        run: |
          rm -rf plateau/*
          rm -rf plateau/{.github,.vscode,.gitkeep,.gitignore,.dockerignore}
          tree -a
      - run: git status
        working-directory: plateau
      - name: Extract PLATEAU-VIEW zip
        run: |
          curl -LO https://github.com/eukarya-inc/PLATEAU-VIEW/archive/refs/heads/main.zip
          unzip main.zip
          shopt -s dotglob
          mv PLATEAU-VIEW-main/* plateau/
          rmdir PLATEAU-VIEW-main
          rm main.zip
      - name: Extract previous PLATEAU-VIEW zip
        run: |
          curl -LO https://github.com/eukarya-inc/PLATEAU-VIEW/archive/refs/heads/plateau.zip
          unzip plateau.zip
          mv PLATEAU-VIEW-plateau plateau-old
          rm plateau.zip
      - name: Extract Re:Earth Visualizer zip
        if: ${{ inputs.update == 'visualizer' || inputs.update == 'all' }}
        run: |
          curl -LO https://github.com/reearth/reearth-visualizer/archive/refs/heads/main.zip
          unzip main.zip
          mv reearth-visualizer-main plateau/editor
          rm main.zip
      - name: Extract previous Re:Earth Visualizer zip
        if: ${{ inputs.update != 'visualizer' && inputs.update != 'all' }}
        run: mv plateau-old/editor plateau/editor
      - name: Extract Re:Earth CMS zip
        if: ${{ inputs.update == 'cms' || inputs.update == 'all' }}
        run: |
          curl -LO https://github.com/reearth/reearth-cms/archive/refs/heads/main.zip
          unzip main.zip
          mv reearth-cms-main plateau/cms
          rm main.zip
      - name: Extract previous Re:Earth CMS zip
        if: ${{ inputs.update != 'cms' && inputs.update != 'all' }}
        run: mv plateau-old/cms plateau/cms
      - name: Extract Re:Earth Flow zip
        if: ${{ inputs.update == 'flow' || inputs.update == 'all' }}
        run: |
          curl -LO https://github.com/reearth/reearth-flow/archive/refs/heads/main.zip
          unzip main.zip
          mv reearth-flow-main plateau/flow
          rm main.zip
      - name: Extract previous Re:Earth Flow zip
        if: ${{ inputs.update != 'flow' && inputs.update != 'all' }}
        run: mv plateau-old/flow plateau/flow
      - run: tree -a
      - name: Commit and push
        working-directory: plateau
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add .
          git commit -m "Update"
          git status
          git push
